name = "NLSE_fiber"
uuid = "18a87857-915e-4f5c-b265-a08c07a9e3ee"
authors = ["Sarthakdsh <sarthakdsh@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
FFTW = "1.8.1"
LinearAlgebra = "1.11.0"
Plots = "1.40.13"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
